config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  get '/register', to: 'users#new'
  resources :users, only: [:new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :connections
  has_many :posts, through: :connections
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :connections
  has_many :categories, through: :connections
  has_many :votes, as: :voteable

  def up_votes
    self.votes.where(vote: true).length
  end

  def down_votes
    self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 32 }
  validates :name, uniqueness: true

  validates :email, presence: true
  validates :email, uniqueness: true

  # validations: false avoid user entering password twice.
  has_secure_password validations: false
  validates :password, presence: true, on: :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: :user_id, class_name: "User"
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:content))
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @posts = Post.all.reverse
    end

    def show
      @post = Post.find(params[:id])
      @comment = Comment.new
      @comments = @post.comments
    end

    def new
      @post = Post.new
    end

    def create
      post = Post.new(post_params)
      post.user = current_user

      # Check if save into datebase.
      if post.save!
        redirect_to posts_path
      else
        render :new
      end
    end

    def vote
      @post = Post.find(params[:id])
      @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

      if @vote.valid?
        flash[:success] = 'Your vote was counted!'
      else
        flash[:error] = "You can only vote for #{@post.title} once!"
      end

      redirect_to :back
    end

    private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 

  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      flash[:notice] = "Login successfully."
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Login failed."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Message Board", root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
            <%= current_user.name %> <span class='caret'></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Register', register_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="row">
  <div class='col-md-1 well text-center'>
    
  </div>
  
</div>

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'Post List'%>

<div class="container">
    <table class="col-md-12 table table-striped">
        <thead>
            <tr>
                <th width="10%">ID</th>
                <th width="60%">Title</th>
                <th width="10%">Poster</th>
                <th width="20%">Created At</th>
            </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td width="10%"><%= post.id.to_s.rjust(3, "0") %></td>
            <td width="60%"><%= link_to post.title, post_path(post) %></td>
            <td width="10%"><%= post.user.name %></td>
            <td width="20%"><%= post.created_at %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<%= render 'shared/title', title: 'New Post'%>

<div class="container">
  <div class="row">
    <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <br>
      <%= f.text_area :content, rows: 5 %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/title', title: "#{@post.title}" %>

<div class="container">
  <hr>
  <div class="row">
    <div class="col-xs-2">
      <div>
      <% if logged_in? %>
        <%= link_to vote_post_path(@post, vote: true), class: "btn btn-primary", method: 'post' do %>
          Like
        <% end %>
      <%end %>
      </div>
      <div><%= @post.total_votes %>Votes</div>
      <div>
      <% if logged_in? %>

        <%= link_to vote_post_path(@post, vote: false), class: "btn btn-danger", method: 'post' do %>
          Dislike
        <% end %>
      <% end %>
      </div>
    </div>

    <div class="col-xs-10">
      <p><%= @post.content %></p>
      <p class="text-right text-bottom text-primary"><%= @post.user.name %></p>
    </div>
  </div>

  <hr>
  <% @comments.each do |comment| %>
  <div class="row">
    <div class="col-xs-10">
      <p><%= comment.content %></p>
    </div>
    <div class="col-xs-2">
      <p class="text-right text-primary"><%= comment.user.name %></p>
    </div>
  </div>
  <% end %>

  <% if logged_in? %>
    <h4>Leave a comment:</h4>
    <%= form_for [@post, @comment] do |f| %>
      <div class="row">
        <div>
          <%= f.text_field :content, maxlength: 96, class: 'col-xs-10' %>
        </div>
        <div class="col-xs-2">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
      <br>
    <% end %>
  <% end %>
</div>

app/views/shared/_title.html.erb
<div class="container">
    <div class="row">
        <div class="col-xd-12">
            <h3><%= title %></h3>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'Register'%>

<div class="container">
    <%= form_for @user do |f| %>
    <div>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :email %>
        <br>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <br>
        <%= f.password_field :password %>
    </div>
    <br>
    <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') %>
    <% end %>
</div>